// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionManagement.Data;

#nullable disable

namespace ProductionManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ProductionManagement.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimalStock")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinimalStock = 100m,
                            Name = "Сталь листовая",
                            Quantity = 500m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 2,
                            MinimalStock = 150m,
                            Name = "Алюминий",
                            Quantity = 80m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 3,
                            MinimalStock = 50m,
                            Name = "Пластик АБС",
                            Quantity = 300m,
                            UnitOfMeasure = "кг"
                        },
                        new
                        {
                            Id = 4,
                            MinimalStock = 500m,
                            Name = "Болт М8",
                            Quantity = 2000m,
                            UnitOfMeasure = "шт"
                        },
                        new
                        {
                            Id = 5,
                            MinimalStock = 50m,
                            Name = "Масло машинное",
                            Quantity = 20m,
                            UnitOfMeasure = "литр"
                        });
                });

            modelBuilder.Entity("ProductionManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimalStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionTimePerUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specifications")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Металлические изделия",
                            Description = "Корпус центробежного насоса",
                            MinimalStock = 10,
                            Name = "Корпус насоса",
                            ProductionTimePerUnit = 120
                        },
                        new
                        {
                            Id = 2,
                            Category = "Металлические изделия",
                            Description = "Стальной кронштейн",
                            MinimalStock = 50,
                            Name = "Кронштейн крепёжный",
                            ProductionTimePerUnit = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Электроника",
                            Description = "Пластиковая панель",
                            MinimalStock = 20,
                            Name = "Панель управления",
                            ProductionTimePerUnit = 60
                        });
                });

            modelBuilder.Entity("ProductionManagement.Models.ProductMaterial", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            MaterialId = 1,
                            QuantityNeeded = 5.5m
                        },
                        new
                        {
                            ProductId = 1,
                            MaterialId = 4,
                            QuantityNeeded = 8m
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 1,
                            QuantityNeeded = 1.2m
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 4,
                            QuantityNeeded = 4m
                        },
                        new
                        {
                            ProductId = 3,
                            MaterialId = 3,
                            QuantityNeeded = 0.8m
                        });
                });

            modelBuilder.Entity("ProductionManagement.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentWorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EfficiencyFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductionLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfficiencyFactor = 1.2f,
                            Name = "Линия А - Металлообработка",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            EfficiencyFactor = 1f,
                            Name = "Линия Б - Сборка",
                            Status = "Stopped"
                        },
                        new
                        {
                            Id = 3,
                            EfficiencyFactor = 0.8f,
                            Name = "Линия В - Пластик",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ProductionManagement.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimatedEndDate = new DateTime(2026, 4, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            ProductionLineId = 1,
                            Progress = 40,
                            Quantity = 5,
                            StartDate = new DateTime(2026, 4, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            EstimatedEndDate = new DateTime(2026, 4, 29, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Progress = 0,
                            Quantity = 20,
                            StartDate = new DateTime(2026, 4, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            EstimatedEndDate = new DateTime(2026, 4, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            ProductionLineId = 3,
                            Progress = 100,
                            Quantity = 10,
                            StartDate = new DateTime(2026, 4, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("ProductionManagement.Models.ProductMaterial", b =>
                {
                    b.HasOne("ProductionManagement.Models.Material", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionManagement.Models.Product", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionManagement.Models.WorkOrder", b =>
                {
                    b.HasOne("ProductionManagement.Models.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionManagement.Models.ProductionLine", "ProductionLine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("ProductionManagement.Models.Material", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("ProductionManagement.Models.Product", b =>
                {
                    b.Navigation("ProductMaterials");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("ProductionManagement.Models.ProductionLine", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
