// <auto-generated />
using System;
using CorporateSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("CorporateSystem.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Электроника",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ноутбук с процессором Intel Core i5, 8 ГБ ОЗУ, SSD 512 ГБ, экран 15.6\" Full HD",
                            Name = "Ноутбук ASUS VivoBook 15",
                            Price = 54990.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Электроника",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6.4\" Super AMOLED, 128 ГБ, камера 50 МП, аккумулятор 5000 мАч",
                            Name = "Смартфон Samsung Galaxy A54",
                            Price = 32990.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Мебель",
                            CreatedAt = new DateTime(2025, 3, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Эргономичное кресло с поддержкой поясницы, регулируемые подлокотники",
                            Name = "Кресло офисное Ergonomic Pro",
                            Price = 18500.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Category = "Аксессуары",
                            CreatedAt = new DateTime(2025, 4, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Беспроводные наушники с активным шумоподавлением, до 30 часов работы",
                            Name = "Наушники Sony WH-1000XM5",
                            Price = 29990.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            Category = "Электроника",
                            CreatedAt = new DateTime(2025, 5, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "4K UHD, IPS, USB-C, 60 Гц, 99% sRGB, поворотная подставка",
                            Name = "Монитор Dell UltraSharp 27\"",
                            Price = 42500.00m,
                            StockQuantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
